# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin_io.xdc

# Block Designs: bd/design_uart/design_uart.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_uart || ORIG_REF_NAME==design_uart} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_dti_uart_0_0/design_uart_dti_uart_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_uart_dti_uart_0_0 || ORIG_REF_NAME==design_uart_dti_uart_0_0} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_microblaze_0_0/design_uart_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_uart_microblaze_0_0 || ORIG_REF_NAME==design_uart_microblaze_0_0} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_mdm_1_0/design_uart_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_uart_mdm_1_0 || ORIG_REF_NAME==design_uart_mdm_1_0} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_clk_wiz_1_0/design_uart_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_uart_clk_wiz_1_0 || ORIG_REF_NAME==design_uart_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_rst_clk_wiz_1_100M_0/design_uart_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_uart_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_uart_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_axi_apb_bridge_0_0/design_uart_axi_apb_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_uart_axi_apb_bridge_0_0 || ORIG_REF_NAME==design_uart_axi_apb_bridge_0_0} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_dlmb_v10_0/design_uart_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_uart_dlmb_v10_0 || ORIG_REF_NAME==design_uart_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_ilmb_v10_0/design_uart_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_uart_ilmb_v10_0 || ORIG_REF_NAME==design_uart_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_dlmb_bram_if_cntlr_0/design_uart_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_uart_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_uart_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_ilmb_bram_if_cntlr_0/design_uart_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_uart_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_uart_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_lmb_bram_0/design_uart_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_uart_lmb_bram_0 || ORIG_REF_NAME==design_uart_lmb_bram_0} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_axi_uart16550_0_0/design_uart_axi_uart16550_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_uart_axi_uart16550_0_0 || ORIG_REF_NAME==design_uart_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_axi_interconnect_0_0/design_uart_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_uart_axi_interconnect_0_0 || ORIG_REF_NAME==design_uart_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_xbar_0/design_uart_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_uart_xbar_0 || ORIG_REF_NAME==design_uart_xbar_0} -quiet] -quiet

# XDC: bd/design_uart/ip/design_uart_microblaze_0_0/design_uart_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_uart_microblaze_0_0 || ORIG_REF_NAME==design_uart_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_uart/ip/design_uart_microblaze_0_0/design_uart_microblaze_0_0_ooc_debug.xdc

# XDC: bd/design_uart/ip/design_uart_mdm_1_0/design_uart_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_uart_mdm_1_0 || ORIG_REF_NAME==design_uart_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_uart/ip/design_uart_mdm_1_0/design_uart_mdm_1_0_ooc_trace.xdc

# XDC: bd/design_uart/ip/design_uart_clk_wiz_1_0/design_uart_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_uart_clk_wiz_1_0 || ORIG_REF_NAME==design_uart_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_uart/ip/design_uart_clk_wiz_1_0/design_uart_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_uart_clk_wiz_1_0 || ORIG_REF_NAME==design_uart_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_uart/ip/design_uart_clk_wiz_1_0/design_uart_clk_wiz_1_0_ooc.xdc

# XDC: bd/design_uart/ip/design_uart_rst_clk_wiz_1_100M_0/design_uart_rst_clk_wiz_1_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_uart_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_uart_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_uart/ip/design_uart_rst_clk_wiz_1_100M_0/design_uart_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_uart_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_uart_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_uart/ip/design_uart_axi_apb_bridge_0_0/design_uart_axi_apb_bridge_0_0_ooc.xdc

# XDC: bd/design_uart/ip/design_uart_dlmb_v10_0/design_uart_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_uart_dlmb_v10_0 || ORIG_REF_NAME==design_uart_dlmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_uart/ip/design_uart_ilmb_v10_0/design_uart_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_uart_ilmb_v10_0 || ORIG_REF_NAME==design_uart_ilmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_uart/ip/design_uart_lmb_bram_0/design_uart_lmb_bram_0_ooc.xdc

# XDC: bd/design_uart/ip/design_uart_axi_uart16550_0_0/design_uart_axi_uart16550_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_uart_axi_uart16550_0_0 || ORIG_REF_NAME==design_uart_axi_uart16550_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_uart/ip/design_uart_axi_uart16550_0_0/design_uart_axi_uart16550_0_0_ooc.xdc

# XDC: bd/design_uart/ip/design_uart_axi_uart16550_0_0/design_uart_axi_uart16550_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_uart_axi_uart16550_0_0 || ORIG_REF_NAME==design_uart_axi_uart16550_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_uart/design_uart_ooc.xdc
