######################################################################
#
# File name : dti_uart_top_elaborate.do
# Created on: Wed Apr 24 17:52:57 +07 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vopt -64 +acc=npr -L xil_defaultlib -L unisims_ver -L secureip -work xil_defaultlib xil_defaultlib.dti_uart_top xil_defaultlib.glbl -o dti_uart_top_opt
