######################################################################
#
# File name : dti_uart_top_compile.do
# Created on: Wed Apr 24 17:52:54 +07 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xil_defaultlib

vmap xil_defaultlib questa_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/4903" "+incdir+../../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/ec67/hdl" "+incdir+/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"dti_uart_top_func_synth.v" \
"../../../../../../../../sim/libs/uart_rx.v" \
"../../../../../../../../sim/libs/uart_tx.v" \

vlog -64 -incr -sv -L xil_defaultlib -work xil_defaultlib  "+incdir+../../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/4903" "+incdir+../../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/ec67/hdl" "+incdir+/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../../dti_uart_top.srcs/sim_1/new/dti_uart_top.sv" \

