#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.1 (64-bit)
#
# Filename    : design_uart.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed May 22 11:45:08 +07 2024
# SW Build 2188600 on Wed Apr  4 18:39:19 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: design_uart.sh [-help]
# usage: design_uart.sh [-lib_map_path]
# usage: design_uart.sh [-noclean_files]
# usage: design_uart.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_uart.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm microblaze_v10_0_6 axi_lite_ipif_v3_0_4 mdm_v3_2_13 lib_cdc_v1_0_2 proc_sys_reset_v5_0_12 lib_pkg_v1_0_2 axi_apb_bridge_v3_0_14 lmb_v10_v3_0_9 lmb_bram_if_cntlr_v4_0_14 blk_mem_gen_v8_4_1 lib_srl_fifo_v1_0_2 axi_uart16550_v2_0_18 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_16 fifo_generator_v13_2_2 axi_data_fifo_v2_1_15 axi_crossbar_v2_1_17)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "design_uart.sh - Script generated by export_simulation (Vivado v2018.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/4903" +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/ec67/hdl" +incdir+"/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "/new_tools/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/new_tools/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/new_tools/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/new_tools/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/new_tools/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/new_tools/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/new_tools/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/new_tools/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/new_tools/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/4903" +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/ec67/hdl" +incdir+"/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "/tools/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/tools/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/new_tools/tools/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/4903" +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/ec67/hdl" +incdir+"/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_uart/ipshared/dti_uart_lib/dti_uart.sv" \
    "$ref_dir/../../../bd/design_uart/ip/design_uart_dti_uart_0_0/sim/design_uart_dti_uart_0_0.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work microblaze_v10_0_6 $vhdlan_opts \
    "$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/6141/hdl/microblaze_v10_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_uart/ip/design_uart_microblaze_0_0/sim/design_uart_microblaze_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mdm_v3_2_13 $vhdlan_opts \
    "$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/351e/hdl/mdm_v3_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_uart/ip/design_uart_mdm_1_0/sim/design_uart_mdm_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/4903" +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/ec67/hdl" +incdir+"/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_uart/ip/design_uart_clk_wiz_1_0/design_uart_clk_wiz_1_0_clk_wiz.v" \
    "$ref_dir/../../../bd/design_uart/ip/design_uart_clk_wiz_1_0/design_uart_clk_wiz_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_uart/ip/design_uart_rst_clk_wiz_1_100M_0/sim/design_uart_rst_clk_wiz_1_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_apb_bridge_v3_0_14 $vhdlan_opts \
    "$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/2f3b/hdl/axi_apb_bridge_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_uart/ip/design_uart_axi_apb_bridge_0_0/sim/design_uart_axi_apb_bridge_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_v10_v3_0_9 $vhdlan_opts \
    "$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/78eb/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_uart/ip/design_uart_dlmb_v10_0/sim/design_uart_dlmb_v10_0.vhd" \
    "$ref_dir/../../../bd/design_uart/ip/design_uart_ilmb_v10_0/sim/design_uart_ilmb_v10_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_bram_if_cntlr_v4_0_14 $vhdlan_opts \
    "$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/226d/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_uart/ip/design_uart_dlmb_bram_if_cntlr_0/sim/design_uart_dlmb_bram_if_cntlr_0.vhd" \
    "$ref_dir/../../../bd/design_uart/ip/design_uart_ilmb_bram_if_cntlr_0/sim/design_uart_ilmb_bram_if_cntlr_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/4903" +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/ec67/hdl" +incdir+"/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/4903" +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/ec67/hdl" +incdir+"/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_uart/ip/design_uart_lmb_bram_0/sim/design_uart_lmb_bram_0.v" \
    "$ref_dir/../../../bd/design_uart/sim/design_uart.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uart16550_v2_0_18 $vhdlan_opts \
    "$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/ce7d/hdl/axi_uart16550_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_uart/ip/design_uart_axi_uart16550_0_0/sim/design_uart_axi_uart16550_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/4903" +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/ec67/hdl" +incdir+"/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/4903" +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/ec67/hdl" +incdir+"/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/4903" +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/ec67/hdl" +incdir+"/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/0cde/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/4903" +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/ec67/hdl" +incdir+"/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/7aff/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_2 $vhdlan_opts \
    "$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/4903" +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/ec67/hdl" +incdir+"/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/4903" +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/ec67/hdl" +incdir+"/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/d114/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/4903" +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/ec67/hdl" +incdir+"/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/d293/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/4903" +incdir+"$ref_dir/../../../../dti_uart_top.srcs/sources_1/bd/design_uart/ipshared/ec67/hdl" +incdir+"/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_uart/ip/design_uart_xbar_0/sim/design_uart_xbar_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_uart xil_defaultlib.glbl -o design_uart_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_uart_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_uart.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/new_data6/workspace/hautx0/Intern_SIP_08_04_2024/sip_2024_apr/dti_uart/fpga/dti_uart_top/dti_uart_top/dti_uart_top.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_uart_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_uart_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_uart.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_uart.sh [-help]\n\
Usage: design_uart.sh [-lib_map_path]\n\
Usage: design_uart.sh [-reset_run]\n\
Usage: design_uart.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
