######################################################################
#
# File name : dti_riscv_top_simulate.do
# Created on: Thu Dec 19 23:04:49 +07 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib dti_riscv_top_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {dti_riscv_top_wave.do}

view wave
view structure
view signals

do {dti_riscv_top.udo}

run 1000ns
