######################################################################
#
# File name : dti_riscv_top_wave.do
# Created on: Thu Dec 19 23:04:49 +07 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
