######################################################################
#
# File name : dti_riscv_top_compile.do
# Created on: Fri Dec 20 08:25:01 +07 2024
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xil_defaultlib

vmap xil_defaultlib questa_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../../dti_riscv_top.srcs/sources_1/bd/design_1/ipshared/4903" "+incdir+/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"dti_riscv_top_time_impl.v" \

vlog -64 -incr -sv -L xil_defaultlib -work xil_defaultlib  "+incdir+../../../../../dti_riscv_top.srcs/sources_1/bd/design_1/ipshared/4903" "+incdir+/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../../dti_riscv_top.srcs/sim_1/new/dti_riscv_top.sv" \

vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../../dti_riscv_top.srcs/sources_1/bd/design_1/ipshared/4903" "+incdir+/tools/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../../dti_riscv_top.srcs/sim_1/imports/libs/uart_rx.v" \


