######################################################################
#
# File name : dti_riscv_top_wave.do
# Created on: Fri Dec 20 08:25:13 +07 2024
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
