######################################################################
#
# File name : dti_riscv_top_simulate.do
# Created on: Fri Dec 20 08:25:13 +07 2024
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
vsim +transport_int_delays +pulse_e/0 +pulse_int_e/0 +pulse_r/0 +pulse_int_r/0 -lib xil_defaultlib dti_riscv_top_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {dti_riscv_top_wave.do}

view wave
view structure
view signals

do {dti_riscv_top.udo}

run 1000ns
