######################################################################
#
# File name : dti_riscv_top_elaborate.do
# Created on: Fri Dec 20 08:25:04 +07 2024
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
vopt -64 +acc=npr -L xil_defaultlib -L simprims_ver -L secureip -work xil_defaultlib xil_defaultlib.dti_riscv_top xil_defaultlib.glbl -o dti_riscv_top_opt
