######################################################################
#
# File name : dti_uart_top_simulate.do
# Created on: Wed Apr 24 17:55:10 +07 2024
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
vsim -lib xil_defaultlib dti_uart_top_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {/new_data6/workspace/hautx0/Intern_SIP_08_04_2024/sip_2024_apr/dti_uart/fpga/dti_uart_top/dti_uart_top/wave.do}

view wave
view structure
view signals

do {dti_uart_top.udo}

run 1000ns
